# Generated by Django 5.1 on 2024-08-27 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_stacking', '0003_habittracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='habitstacking',
            name='goal',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('NO_GOAL', 'No Goal'), ('SPECIFIC_DAYS', 'Specific Days')], default='DAILY', max_length=20),
        ),
        migrations.AlterField(
            model_name='habitstackinglog',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='habitstacking',
            unique_together={('user', 'habit1', 'habit2')},
        ),
        migrations.AddField(
            model_name='habitstacking',
            name='specific_days',
            field=models.ManyToManyField(blank=True, to='habit_stacking.weekday'),
        ),
        migrations.DeleteModel(
            name='HabitTracking',
        ),
    ]
