# Generated by Django 5.1 on 2024-08-28 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_stacking', '0006_alter_habitstacking_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='habitstacking',
            name='custom_habit1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='habitstacking',
            name='custom_habit2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='habitstacking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='habitstacking',
            name='predefined_habit1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habit1_set', to='habit_stacking.predefinedhabit'),
        ),
        migrations.AddField(
            model_name='habitstacking',
            name='predefined_habit2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habit2_set', to='habit_stacking.predefinedhabit'),
        ),
        migrations.AlterUniqueTogether(
            name='habitstacking',
            unique_together={('user', 'predefined_habit1', 'custom_habit1', 'predefined_habit2', 'custom_habit2')},
        ),
        migrations.RemoveField(
            model_name='habitstacking',
            name='habit1',
        ),
        migrations.RemoveField(
            model_name='habitstacking',
            name='habit2',
        ),
    ]
