# Generated by Django 5.1 on 2024-09-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_stacking', '0007_predefinedhabit_habitstacking_custom_habit1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitstacking',
            name='specific_days',
        ),
        migrations.AlterField(
            model_name='habitstacking',
            name='goal',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('NO_GOAL', 'No Goal')], default='DAILY', max_length=20),
        ),
        migrations.DeleteModel(
            name='Weekday',
        ),
    ]
