# Generated by Django 5.1 on 2024-09-26 07:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_stacking', '0008_remove_habitstacking_specific_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achieved', models.DateField(default=django.utils.timezone.now)),
                ('days_completed', models.IntegerField()),
                ('habit_stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habit_stacking.habitstacking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'habit_stack', 'days_completed')},
            },
        ),
    ]
