# Generated by Django 5.1 on 2024-08-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='../ftpfkey8ogd3f06e0vle', upload_to='images/'),
        ),
    ]
