# Generated by Django 5.1 on 2024-08-22 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couplings', '0001_initial'),
        ('habit_tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habittracking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='habittracking',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='habittracking',
            name='coupling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couplings.coupling'),
        ),
        migrations.AlterField(
            model_name='habittracking',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='habittracking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='habittracking',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='habittracking',
            name='habit',
        ),
    ]
