# Generated by Django 5.1 on 2024-08-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracking', '0003_habitschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='habittracking',
            name='goal',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('SPECIFIC_DAYS', 'Specific Days')], default='DAILY', max_length=20),
        ),
        migrations.AddField(
            model_name='habittracking',
            name='specific_days',
            field=models.ManyToManyField(blank=True, to='habit_tracking.dayofweek'),
        ),
        migrations.DeleteModel(
            name='HabitSchedule',
        ),
    ]
