# Generated by Django 5.1 on 2024-08-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracking', '0005_remove_habittracking_specific_days_delete_dayofweek_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='habittracking',
            name='specific_days',
        ),
        migrations.AddField(
            model_name='habittracking',
            name='specific_days',
            field=models.ManyToManyField(blank=True, to='habit_tracking.dayofweek'),
        ),
    ]
