# Generated by Django 5.1 on 2024-08-23 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracking', '0006_dayofweek_remove_habittracking_specific_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayofweek',
            name='day_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='habittracking',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
