# Generated by Django 5.1 on 2024-08-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracking', '0007_alter_dayofweek_day_name_alter_habittracking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habittracking',
            name='date',
            field=models.DateField(),
        ),
    ]
