# Generated by Django 5.1 on 2024-08-21 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit1', to='habits.habit')),
                ('habit2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit2', to='habits.habit')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('habit1', 'habit2', 'owner')},
            },
        ),
    ]
